<a id='chapter10'></a>

# CHAPTER 10 - Tuples

## EXERCISES

#### Exercise 1

Create a tuple with the following items: `1, 1, 2, 3, 5`. Feed the tuple to the `sum()` built-in function and check the result.

In [2]:
tuple = (1, 1, 2, 3, 5)

total_sum = sum(tuple)

print(f"The sum of the elements in the tuple is: {total_sum}")

The sum of the elements in the tuple is: 12

#### Exercise 2

Unpack the following tuple into meaningful variables and display them

```python
ph_info = ('Philippines', 'Manila', 103.3) # The last number is the Population in Millions as of 2016
```

In [5]:
DataTuple = ("Alice", 25, "Software Engineer")

name, age, profession = DataTuple

print(f"Name: {name}")
print(f"Age: {age}")
print(f"Profession: {name}")

Name: Alice
Age: 25
Profession: Alice